config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'

  resources :message_rooms, only: [:new, :create, :show, :index]
  root 'message_rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :message_room

  validates :body, presence: true, length: {minimum: 1, maximum: 1000}

end

app/models/message_room.rb
class MessageRoom < ApplicationRecord
	#ensure that message rooms are tied to each user
	belongs_to :user
	#tie messsages to the chat rooms they were created in
	has_many :messages, dependent: :destroy
	#make sure each chat room must have a room name, specified by the user
	#validates :room_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #user will have 1 or more message room(s)
  has_many :message_rooms, dependent: :destroy
  #user will have messages created during message sessions
  has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	
	before_action :authenticate_user!

	private

	#Require first and last name during sign up
	#in addition to other required params
	def configure_permitted_parameters()
		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
	end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
	#This is left blank as messages are handled via React
end

app/controllers/message_rooms_controller.rb
class MessageRoomsController < ApplicationController

	#get all the message rooms and pass them into the Draper decorator
	#this remove the needs to write subclasses
	#inherit all methods defined in the MessageRoomDecorator decorator\
	#@params: Nil
	#@return: Decorator-modified message rooms
	def index
		@message_rooms = MessageRoomDecorator.decorate_collection(MessageRoom.all)
	end

	#get a specfic message room based on ID
	#serialized the message room using serializer
	#@params: Nil
	#@return: Nil
	def show
		@message_room = MessageRoom.find(params[:id])
		@json_object = MessageRoomsSerializer.new(@message_room).as_json
	end

	#Create a new message room given a name
	#@params: Nil
	#@return: Nil
	def new
		@message_room = MessageRoom.new
	end

	#Create a new message room given a name
	#@params: Nil
	#@return: Nil
	def create
		@message_room = current_user.message_rooms.new(room_params)
		if @message_room.save
			flash[:success] = "Successuflly created new message room"
			redirect_to message_rooms_path
		else
			render 'new'
		end
	end

	private

		def room_params
			params.require(:message_room).permit(:room_name)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/message_rooms_helper.rb
module MessageRoomsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", :name => "viewport"}/
    %title WelcomeTechChatApplication
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = action_cable_meta_tag 
  %body
    %container{:class => "wrapper fadeInDown"}
      .col-sm-12
        - if user_signed_in?
          %p
            = link_to 'Logout', destroy_user_session_path, class: "text-right", method: :delete
        = yield
    }

app/views/message_rooms/_message_room.html.haml
%li
  = link_to "Enter #{message_room.id}", message_room_path(message_room)

app/views/message_rooms/index.html.haml
%container{:class => "wrapper fadeInDown"}
  %h2.text-center Welcome Tech's Message Rooms
  %br
  %small
    = link_to 'New message room', new_message_room_path, class: 'btn btn-primary btn-sx'

%table.table.table-hover
  %thead
    %tr
      %th Title
      %th Owner
      %th Date Created
      %th Action
  %tbody
    - @message_rooms.each do |message_room|
      %tr
        %td
          = message_room.get_room_name
        %td
          = message_room.owner
        %td
          = message_room.created_at
        %td
          = link_to "Enter", message_room_path(message_room), class: "btn btn-sm btn-primary"

app/views/message_rooms/new.html.haml
%div{:class => "wrapper fadeInDown" }
  %h2.text-center Create New Message Room
  %br
  %small
    = link_to 'Back', message_rooms_path, class: 'btn btn-primary btn-sx' 

= form_for @message_room do |f|
  .form-group
    = f.label :room_name
    = f.text_field :room_name, autofocus: true, class: 'form-control'
    %center
      = f.submit "Save", class: 'btn btn-primary btn-sx'

app/views/message_rooms/show.html.haml
%container{:class => "wrapper fadeInDown"}
%center
  = @message_room.room_name
  %br
  %small 
    = link_to 'Back', message_rooms_path, class: 'btn btn-primary btn-sx'  

= react_component('MessageRoom', { message_room: @json_object })